name: Run build for dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0

      - uses: actions/checkout@v4.1.1
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.NGINX_PAT }}

      - name: Set up Node.js 16.x
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x

      - name: Install dependencies
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        run: npm ci

      - name: Run build
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        run: |
          npm run build
          npm run package

      - name: Commit changes
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: 'Update dist/ after build'
