name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
  check-dist:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          corepack yarn install

      - name: Lint the code
        run: |
          corepack yarn run lint

      - name: Run format check
        run: |
          corepack yarn run format

      - name: Check for uncommitted changes
        run: |
          if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after linting.  See status below:"
            git diff
            exit 1
          fi
